version: '3.1'

services:

  mongodb:
    image: healyou/mongo-enterprise:5.0
    container_name: mongo-db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
#  TODO    как красиво проверить в mongo
      test: echo 'db.runCommand("ping").ok' | mongo admin -u mongoadmin -p mongoadmin --quiet | grep 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  mongo-express:
    links:
      - mongodb
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8081:8081
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
#      interval: 10s
#      timeout: 3s
#      retries: 5
#      start_period: 5s
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin