version: '3.2'

services:

  redis:
    image: redis:6.2.6-alpine
    container_name: auth-redis-db
    command: redis-server --appendonly yes --appendfsync everysec --requirepass redis
    ports:
     - 6379:6379
    restart: always
    volumes:
     - ./data:/data
    healthcheck:
      test: ["CMD", "redis-cli","-a","redis","ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 5s

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:redis-commander-210
    restart: always
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - HTTP_USER=redis
      - HTTP_PASSWORD=redis
    ports:
      - 8081:8081
    depends_on:
      redis:
        condition: service_healthy
