version: '3.2'

services:

  redis:
    image: redis:6.2.6-alpine
    container_name: auth-redis-db
    command: redis-server --appendonly yes --appendfsync everysec --requirepass redis
    ports:
     - 6379:6379
    restart: always
    volumes:
     - ./data:/data
    healthcheck:
      test: ["CMD", "redis-cli","-a","redis","ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 5s
